SHORTENER_API_KEY = '...';  // Specify your API key

PUBLISHER_NAME = 'こぐまやん';
EVENT_NAME = 'ゲームマーケット2018春';
EVENT_SHORT_NAME = 'ゲムマ2018春';
BOOTH_IDENTIFIER = '土-E65';
PUBLISHER_SIGNATURE = Utilities.formatString(
    '%s＠%s[%s]', 
    PUBLISHER_NAME, 
    EVENT_SHORT_NAME, 
    BOOTH_IDENTIFIER
);
RECEPT_START_DATE = new Date('2018-05-05T01:00:00.000Z');
RECEPT_END_DATE = new Date('2018-05-05T05:00:00.000Z');

SPREADSHEET_NAME = '予約管理表';
RESERV_SHEET_NAME = '予約一覧';
ITEM_SHEET_NAME = '商品一覧';

PROP_NOTIFIED_DATE = 'NOTIFIED_DATE';